### ISSUE TITLE
in SARCBertclassifier.py, there's a bug

### ISSUE THREAD

**Issue by wuruochen9** [PradeepNalluri/Prefix-Tuning-Bert#2]
outputs = self.bert(
            input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            head_mask=head_mask,
            inputs_embeds=inputs_embeds,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
            prefix_embeddings=prefix_embds,

It says unexpected keyword " prefix_embeddings"

**Comment by PradeepNalluri** [comment]
Hey @wuruochen9, did you install the updated transformers package?

**Comment by Sudhandar** [comment]
@PradeepNalluri I have the same issue as well (even after installing the updated transformers package). It will be really helpful if you could fix this error. Your help is very much appreciated. 

I'm getting this error if I skip this line, 

`cd  transformers; pip install -e .;`

But if i execute this line and then run train.py, I'm getting the following error,

> ImportError: cannot import name 'BertTokenizer' from 'transformers' (unknown location)

**Comment by PradeepNalluri** [comment]
I see. Sorry that you are facing this issue. I will work on the fix and push it soon.
Thanks!

**Comment by Sudhandar** [comment]
Great, thank you so much!

**Comment by PradeepNalluri** [comment]
Hey @Sudhandar, I am able to start the training without any issues. 
![image](https://user-images.githubusercontent.com/25664333/176084135-8264f142-e51e-40b2-a916-de777f074be9.png)

I am not sure why you are facing an issue.

**Comment by Sudhandar** [comment]
@PradeepNalluri I found the mistake I made. I was running on Google Colab and used condacolab to use python3.6 and created the environment. Turns out colab was still using python3.7 and I had to change it to 3.6 and it's working now.

Thank you so much for your quick response. Just a small suggestion, if possible try to post a blog explaining the working (code) of prefix tuning a BERT model to perform classification. It's still new and there are no tutorials out there.  It will gain you a lot of recognition.
